version: '3'

services:
  app:
    depends_on:
      - mysql
    build:
      context: '.'
    ports:
      - '3000:3000'
    volumes:
      - ".:/app"
    env_file:
      - .env
  # batch:
  #   image: node:10.2.1
  #   command: npm run start:batch
  #   build:
  #     context: '.'
  #   volumes:
  #     - ".:/app"
  #   env_file:
  #     - .env
  mysql:
    image: mysql:5.7 # wait for https://github.com/mysqljs/mysql/pull/1962
    volumes:
     - ./data/db:/var/lib/mysql
    env_file:
      - .env
    # redis:
  #   image: 'redis:3.2-alpine'
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - 'redis:/data'